pull_request_rules:
  - name: Dependabot
    conditions:
      - "status-success=BDDTDDKata"
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: merge